"""
Configuration settings for the RDS Generator application
"""

# Default image parameters
DEFAULT_IMAGE_WIDTH = 512
DEFAULT_IMAGE_HEIGHT = 512
DEFAULT_DENSITY = 50
DEFAULT_DOT_SIZE = 2
DEFAULT_DOT_SHAPE = '四角'
DEFAULT_BG_COLOR = "#FFFFFF"
DEFAULT_DOT_COLOR = "#000000"

# Default stereo parameters
DEFAULT_DISPARITY_ARCSEC = 20
DEFAULT_DISTANCE_CM = 57.0
DEFAULT_PPI = 96
DEFAULT_DISPLAY_MODE = 'ステレオペア (平行法)'

# Default shape parameters
DEFAULT_SHAPE_TYPE = '四角形'
DEFAULT_SHAPE_MODE = '面'
DEFAULT_BORDER_WIDTH = 2
DEFAULT_SHAPE_WIDTH = 256
DEFAULT_SHAPE_HEIGHT = 256

# Default batch parameters
DEFAULT_BATCH_START = -100
DEFAULT_BATCH_END = 100
DEFAULT_BATCH_STEP = 20

# UI constraints
MIN_IMAGE_SIZE = 128
MAX_IMAGE_SIZE = 1024
IMAGE_SIZE_STEP = 128

MIN_DENSITY = 1
MAX_DENSITY = 100

MIN_DOT_SIZE = 1
MAX_DOT_SIZE = 10

MIN_DISPARITY = -600
MAX_DISPARITY = 600

MIN_DISTANCE = 30.0
MAX_DISTANCE = 200.0

MIN_PPI = 72
MAX_PPI = 400

MIN_BORDER_WIDTH = 1
MAX_BORDER_WIDTH = 20

MIN_SHAPE_SIZE = 10

MIN_BATCH_DISPARITY = -1000
MAX_BATCH_DISPARITY = 1000
MIN_BATCH_STEP = 1
MAX_BATCH_STEP = 200

# FFT parameters
DEFAULT_PAD_WIDTH = 32
DEFAULT_NOISE_STD = 0.5
RANDOM_SEED_LEFT = 42
RANDOM_SEED_RIGHT = 43
RANDOM_SEED_NOISE = 123